#Requires -Version 7.2
<#
    InvokeBuild tasks for PSAzureDevOpsGraph.

    PreTag is deliberately absent from the default task. It seals a FINISHED
    iteration, and a half-finished one should still be able to build green.
#>

$script:ModuleName = 'PSAzureDevOpsGraph'
$script:Source     = "$BuildRoot/src/$script:ModuleName"
$script:OutputDir  = "$BuildRoot/output/$script:ModuleName"

task . Clean, Lint, Build, Test

task Clean {
    if (Test-Path -LiteralPath "$BuildRoot/output") {
        Remove-Item -LiteralPath "$BuildRoot/output" -Recurse -Force
    }
    if (Test-Path -LiteralPath "$BuildRoot/testResults") {
        Remove-Item -LiteralPath "$BuildRoot/testResults" -Recurse -Force
    }
    Write-Build Green 'Clean: output/ and testResults/ removed.'
}

task Lint {
    # A gate, not a report.
    $findings = Invoke-ScriptAnalyzer -Path "$BuildRoot/src" -Recurse `
        -Settings "$BuildRoot/PSScriptAnalyzerSettings.psd1"
    if ($findings) {
        $findings | Format-Table -AutoSize | Out-String | Write-Host
        throw "PSScriptAnalyzer reported $($findings.Count) finding(s)."
    }
    Write-Build Green 'Lint: 0 findings.'
}

task Build {
    $null = New-Item -ItemType Directory -Path $script:OutputDir -Force

    $private = @(Get-ChildItem -LiteralPath "$script:Source/Private" -Filter *.ps1 -Recurse -File |
            Sort-Object FullName)
    $public = @(Get-ChildItem -LiteralPath "$script:Source/Public" -Filter *.ps1 -File |
            Sort-Object Name)

    $sb = [System.Text.StringBuilder]::new()
    $null = $sb.AppendLine('# This file is auto-generated by the build. Do not edit.')
    $null = $sb.AppendLine('# Source of truth is src/PSAzureDevOpsGraph/{Private,Public}.')
    $null = $sb.AppendLine('')
    # A real assignment, emitted as code. Concatenation moves what $PSScriptRoot
    # means, so assets resolve from a variable that means the same thing under
    # the build and under the committed dev loader.
    $null = $sb.AppendLine('$script:ModuleRoot = $PSScriptRoot')
    $null = $sb.AppendLine('')

    foreach ($file in ($private + $public)) {
        $relative = $file.FullName.Substring($script:Source.Length + 1).Replace([char] 92, [char] 47)
        $null = $sb.AppendLine("# --- $relative ---")
        $null = $sb.AppendLine((Get-Content -LiteralPath $file.FullName -Raw))
        $null = $sb.AppendLine('')
    }

    # A real call listing every exported name as a string constant.
    $names = $public.BaseName
    $null = $sb.AppendLine("Export-ModuleMember -Function $(($names | ForEach-Object { "'$_'" }) -join ', ')")

    Set-Content -LiteralPath "$script:OutputDir/$script:ModuleName.psm1" -Value $sb.ToString() -Encoding utf8NoBOM
    Copy-Item -LiteralPath "$script:Source/$script:ModuleName.psd1" -Destination $script:OutputDir -Force

    # Culture directories, or Get-Help finds no about_ topic. The most commonly
    # missed step in a module build, because everything else works without it.
    foreach ($dir in Get-ChildItem -LiteralPath $script:Source -Directory) {
        if ($dir.Name -match '^[a-z]{2}(-[A-Za-z]{2,4})?$') {
            Copy-Item -LiteralPath $dir.FullName -Destination $script:OutputDir -Recurse -Force
            Write-Build Green "  culture directory copied: $($dir.Name)"
        }
    }

    Write-Build Green "Build: $($private.Count) private + $($public.Count) public into $script:OutputDir."
}

task Test {
    $cfg = New-PesterConfiguration
    $cfg.Run.Path          = "$BuildRoot/tests"
    $cfg.Run.Throw         = $true
    # Without PassThru, Invoke-Pester -Configuration RETURNS NOTHING. The gate
    # below then reads a null result: $percent comes out 0, $target comes out
    # empty string, and `0 -lt ''` is false, so the coverage gate passes every
    # run no matter what coverage actually is. It is a gate that cannot fail.
    $cfg.Run.PassThru      = $true
    $cfg.Run.FailOnNullOrEmptyForEach = $false
    $cfg.Should.DisableV5  = $true
    $cfg.Output.Verbosity  = 'Detailed'
    $cfg.Filter.ExcludeTag = 'PreTag'
    $cfg.CodeCoverage.Enabled = $true
    $cfg.CodeCoverage.Path    = "$script:OutputDir/$script:ModuleName.psm1"

    # Declared once. The gate below reads it back off the result rather than
    # keeping a second copy of the number in a parameter; two thresholds in two
    # places drift, and the drift is silent because both halves keep working.
    $cfg.CodeCoverage.CoveragePercentTarget = 70

    $result = Invoke-Pester -Configuration $cfg

    $coverage = $result.CodeCoverage
    $percent  = [math]::Round($coverage.CoveragePercent, 2)
    $target   = $coverage.CoveragePercentTarget
    if ($percent -lt $target) {
        throw "Line coverage $percent% is below the target of $target%. Raise coverage, or lower the target deliberately and say so."
    }
    Write-Build Green "Line coverage: $percent% (target $target%)"
}

task PreTag {
    $cfg = New-PesterConfiguration
    $cfg.Run.Path         = "$BuildRoot/tests"
    $cfg.Run.Throw        = $true
    # Same reason as the Test task: without this the guard below reads a null
    # result, counts zero, and throws its own "selected no test" message on
    # every run - including runs where the seals all passed.
    $cfg.Run.PassThru     = $true
    $cfg.Should.DisableV5 = $true
    $cfg.Filter.Tag       = 'PreTag'
    $cfg.Output.Verbosity = 'Detailed'

    $result = Invoke-Pester -Configuration $cfg

    # Count what RAN. Discovery walks the whole tests path before the tag filter
    # applies, so TotalCount is never zero and a guard written against it can
    # never fire.
    if (($result.PassedCount + $result.FailedCount) -eq 0) {
        throw 'The PreTag filter selected no test at all. A gate that grades nothing is not a gate.'
    }
    Write-Build Green "PreTag: $($result.PassedCount) passed."
}
