#Requires -Version 7.2

<#
    InvokeBuild tasks for PSAzureDevOpsGraph.

    Order is Clean, Lint, Build, Test, because each stage is a precondition for
    the next and a failure is cheapest where it is closest to its cause. PreTag
    is deliberately NOT in the default task: a half-finished iteration should
    still be able to run a green build.
#>

$script:ModuleName = 'PSAzureDevOpsGraph'
$script:SourcePath = "$BuildRoot/src/$script:ModuleName"
$script:OutputPath = "$BuildRoot/output/$script:ModuleName"

task . Clean, Lint, Build, Test

task Clean {
    if (Test-Path -LiteralPath "$BuildRoot/output") {
        Remove-Item -LiteralPath "$BuildRoot/output" -Recurse -Force
    }
    Write-Build Green 'Removed output/'
}

task Lint {
    $findings = Invoke-ScriptAnalyzer -Path $script:SourcePath -Recurse `
        -Settings "$BuildRoot/PSScriptAnalyzerSettings.psd1"
    if ($findings) {
        $findings | Format-Table -AutoSize | Out-String | Write-Host
        throw "PSScriptAnalyzer reported $($findings.Count) finding(s)."
    }
    Write-Build Green 'PSScriptAnalyzer: 0 findings'
}

task Build {
    $null = New-Item -ItemType Directory -Path $script:OutputPath -Force

    $sb = [System.Text.StringBuilder]::new()
    $null = $sb.AppendLine('# This file is auto-generated by the build. Do not edit.')
    $null = $sb.AppendLine('$script:ModuleRoot = $PSScriptRoot')
    $null = $sb.AppendLine()

    # Private first and recursively, then Public. The same order the dev loader
    # uses; a different order works until a public function calls a private one
    # at load time. Sorted by full path so nested subfolders are stable.
    $sources = @(Get-ChildItem -LiteralPath "$script:SourcePath/Private" -Filter *.ps1 -Recurse -File | Sort-Object FullName) +
    @(Get-ChildItem -LiteralPath "$script:SourcePath/Public" -Filter *.ps1 -File | Sort-Object Name)
    foreach ($file in $sources) {
        $null = $sb.AppendLine((Get-Content -LiteralPath $file.FullName -Raw))
        $null = $sb.AppendLine()
    }

    # Emitted as code, never as a comment. A generated file is the one place a
    # commented-out line is cheapest to write by accident.
    $names = @(Get-ChildItem -LiteralPath "$script:SourcePath/Public" -Filter *.ps1 -File | Sort-Object Name).BaseName
    $null = $sb.AppendLine("Export-ModuleMember -Function $(($names | ForEach-Object { "'$_'" }) -join ', ')")

    Set-Content -LiteralPath "$script:OutputPath/$script:ModuleName.psm1" -Value $sb.ToString() -Encoding utf8NoBOM
    Copy-Item -LiteralPath "$script:SourcePath/$script:ModuleName.psd1" -Destination $script:OutputPath -Force

    # Culture directories must be copied or Get-Help finds no about_ topics.
    foreach ($culture in Get-ChildItem -LiteralPath $script:SourcePath -Directory |
        Where-Object { $_.Name -notin 'Public', 'Private' }) {
        Copy-Item -LiteralPath $culture.FullName -Destination $script:OutputPath -Recurse -Force
    }

    Write-Build Green "Built $($sources.Count) source file(s), exporting $($names.Count) function(s)"
}

task Test {
    $cfg = New-PesterConfiguration
    $cfg.Run.Path = "$BuildRoot/tests"
    $cfg.Run.Throw = $true
    # Without PassThru, Invoke-Pester returns nothing, $result is $null, and the
    # coverage gate below compares 0 against nothing and can never fire. The
    # gate went green on its first run for that reason and not for a good one.
    $cfg.Run.PassThru = $true
    $cfg.Run.FailOnNullOrEmptyForEach = $false
    $cfg.Should.DisableV5 = $true
    $cfg.Filter.ExcludeTag = 'PreTag'
    $cfg.CodeCoverage.Enabled = $true
    $cfg.CodeCoverage.Path = "$script:OutputPath/$script:ModuleName.psm1"
    $cfg.CodeCoverage.CoveragePercentTarget = 40
    $cfg.Output.Verbosity = 'Detailed'

    $result = Invoke-Pester -Configuration $cfg

    # Read the target back off the result rather than keeping a second copy of
    # the number. Two thresholds in two places drift, and the drift is silent.
    $coverage = $result.CodeCoverage
    $percent = [math]::Round($coverage.CoveragePercent, 2)
    $target = $coverage.CoveragePercentTarget
    if ($percent -lt $target) {
        throw "Line coverage $percent% is below the target of $target%. Raise coverage, or lower the target deliberately and say so."
    }
    Write-Build Green "Line coverage: $percent% (target $target%)"
}

task PreTag {
    $cfg = New-PesterConfiguration
    $cfg.Run.Path = "$BuildRoot/tests"
    $cfg.Run.Throw = $true
    $cfg.Run.PassThru = $true
    $cfg.Run.FailOnNullOrEmptyForEach = $false
    $cfg.Should.DisableV5 = $true
    $cfg.Filter.Tag = 'PreTag'
    $cfg.Output.Verbosity = 'Detailed'

    $result = Invoke-Pester -Configuration $cfg

    # Count what RAN. Discovery walks the whole tests path before the tag filter
    # applies, so TotalCount is never zero and a guard written against it can
    # never fire.
    if (($result.PassedCount + $result.FailedCount) -eq 0) {
        throw 'The PreTag filter selected no test at all. A gate that grades nothing is not a gate.'
    }
    Write-Build Green "PreTag: $($result.PassedCount) passed"
}
