#Requires -Version 7.2
<#
    InvokeBuild tasks for PSAzureDevOpsGraph.

    Read by the conformance suite as SYNTAX, not as text. Every assertion over
    this file was once a regex, and every one of them was satisfied by a block
    comment quoting the line it looked for while the real code was deleted. A
    comment is not a task, an assignment, or a gate.
#>
param(
    [int] $CoverageTarget = 40
)

$ModuleName = 'PSAzureDevOpsGraph'
$SourceRoot = "$BuildRoot/src/$ModuleName"
$OutputRoot = "$BuildRoot/output/$ModuleName"

task . Clean, Lint, Build, Test

task Clean {
    if (Test-Path "$BuildRoot/output") {
        Remove-Item "$BuildRoot/output" -Recurse -Force
    }
    if (Test-Path "$BuildRoot/testResults") {
        Remove-Item "$BuildRoot/testResults" -Recurse -Force
    }
}

task Lint {
    $findings = @(
        Invoke-ScriptAnalyzer -Path $SourceRoot -Recurse `
            -Settings "$BuildRoot/PSScriptAnalyzerSettings.psd1"
    )
    if ($findings.Count -gt 0) {
        $findings | Format-Table -AutoSize RuleName, Severity, ScriptName, Line, Message |
            Out-String | Write-Build Yellow
        throw "PSScriptAnalyzer reported $($findings.Count) finding(s)."
    }
    Write-Build Green 'Lint clean.'
}

task Build {
    $null = New-Item -ItemType Directory -Path $OutputRoot -Force

    $private = @(Get-ChildItem "$SourceRoot/Private" -Filter *.ps1 -File -Recurse -ErrorAction SilentlyContinue |
            Sort-Object FullName)
    $public = @(Get-ChildItem "$SourceRoot/Public" -Filter *.ps1 -File -ErrorAction SilentlyContinue |
            Sort-Object Name)

    $builder = [System.Text.StringBuilder]::new()
    $null = $builder.AppendLine('# ------------------------------------------------------------------')
    $null = $builder.AppendLine("# This file is auto-generated by $ModuleName.build.ps1. Do not edit it.")
    $null = $builder.AppendLine('# Edit the files under src/ and run ./build.ps1 instead.')
    $null = $builder.AppendLine('# ------------------------------------------------------------------')
    $null = $builder.AppendLine('')
    # Concatenation moves what $PSScriptRoot means, so assets must resolve from
    # a variable that is the same under the build and under a dev loader.
    $null = $builder.AppendLine('$script:ModuleRoot = $PSScriptRoot')
    $null = $builder.AppendLine('')

    foreach ($file in ($private + $public)) {
        $null = $builder.AppendLine("# --- $($file.Name) ---")
        $null = $builder.AppendLine((Get-Content -LiteralPath $file.FullName -Raw))
        $null = $builder.AppendLine('')
    }

    $exported = @($public.BaseName | Sort-Object)
    $names = ($exported | ForEach-Object { "'$_'" }) -join ', '
    $null = $builder.AppendLine("Export-ModuleMember -Function $names")

    Set-Content -LiteralPath "$OutputRoot/$ModuleName.psm1" -Value $builder.ToString() -Encoding utf8NoBOM
    Copy-Item -LiteralPath "$SourceRoot/$ModuleName.psd1" -Destination "$OutputRoot/$ModuleName.psd1" -Force

    # Culture directories, or Get-Help finds no about_ topics.
    foreach ($culture in @(Get-ChildItem $SourceRoot -Directory |
                Where-Object { $_.Name -match '^[a-z]{2}(-[A-Za-z]{2,4})?$' })) {
        Copy-Item -LiteralPath $culture.FullName -Destination $OutputRoot -Recurse -Force
    }

    Write-Build Green "Built $OutputRoot/$ModuleName.psm1 from $($private.Count) private and $($public.Count) public files."
}

task Test {
    $configuration = New-PesterConfiguration
    $configuration.Run.Path = "$BuildRoot/tests"
    $configuration.Run.PassThru = $true
    # Run.Throw, never Run.Exit: Run.Exit makes Pester kill the host process.
    $configuration.Run.Throw = $true
    $configuration.Should.DisableV5 = $true
    # A half-finished iteration must still be able to build green.
    $configuration.Filter.ExcludeTag = 'PreTag'
    $configuration.Output.Verbosity = 'Detailed'
    $configuration.CodeCoverage.Enabled = $true
    # Coverage against the built psm1, not src/: src counts lines the build
    # never assembled.
    $configuration.CodeCoverage.Path = "$OutputRoot/$ModuleName.psm1"
    $configuration.CodeCoverage.OutputPath = "$BuildRoot/testResults/coverage.xml"

    $result = Invoke-Pester -Configuration $configuration

    $percent = [double] $result.CodeCoverage.CoveragePercent
    Write-Build Green ("Coverage {0:N2}% against a target of {1}%." -f $percent, $CoverageTarget)

    # CoveragePercentTarget only reports. This throw is the gate.
    if ($percent -lt $CoverageTarget) {
        throw ("Coverage {0:N2}% is below the target of {1}%." -f $percent, $CoverageTarget)
    }
}

task PreTag {
    $configuration = New-PesterConfiguration
    $configuration.Run.Path = "$BuildRoot/tests"
    $configuration.Run.PassThru = $true
    $configuration.Run.Throw = $true
    $configuration.Should.DisableV5 = $true
    $configuration.Filter.Tag = 'PreTag'
    $null = Invoke-Pester -Configuration $configuration
    Write-Build Green 'PreTag checks passed.'
}
