function ConvertTo-AzDoGraphHtml {
    <#
    .SYNOPSIS
        A graph as a single self-contained HTML page.
    .DESCRIPTION
        Self-contained means self-contained: no external script, stylesheet,
        @import, font, image or http(s):// reference of any kind, so the page
        renders from a file:// URL on a machine with no network. That rules out
        an xmlns on the inline SVG too -- HTML5 does not need one, and the usual
        value is a URL.

        Unresolved references get their own section and their own colour. They
        are the answer the tool exists to give; a broken pipeline that renders
        identically to a clean one makes the tool worst exactly where it would be
        most useful.
    .PARAMETER Graph
        A graph from Get-AzDoPipelineDependencyGraph.
    .OUTPUTS
        System.String
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param([Parameter(Mandatory)] $Graph)

    $esc = {
        param([string] $Text)
        if ($null -eq $Text) { return '' }
        $Text.Replace('&', '&amp;').Replace('<', '&lt;').Replace('>', '&gt;').Replace('"', '&quot;')
    }

    $real = @{}
    foreach ($node in $Graph.nodes) { $real[$node.id] = $node }

    $unresolved = @($Graph.edges | Where-Object { $_.kind -eq 'unresolved' })
    $byKind = $Graph.nodes | Group-Object -Property kind

    $inDegree = @{}
    foreach ($edge in $Graph.edges) {
        if (-not $inDegree.ContainsKey($edge.to)) { $inDegree[$edge.to] = 0 }
        $inDegree[$edge.to]++
    }

    $sb = [System.Text.StringBuilder]::new()
    $null = $sb.AppendLine('<!doctype html>')
    $null = $sb.AppendLine('<html lang="en"><head><meta charset="utf-8">')
    $null = $sb.AppendLine('<meta name="viewport" content="width=device-width,initial-scale=1">')
    $null = $sb.AppendLine("<title>Pipeline dependency graph &mdash; $(& $esc $Graph.project)</title>")
    $null = $sb.AppendLine('<style>')
    $null = $sb.AppendLine(':root{--bg:#fbfbfa;--fg:#1f2328;--muted:#6b7280;--line:#e5e7eb;--pipeline:#dbeafe;--yaml:#ecfdf5;--repo:#fef3c7;--bad:#fee2e2;--badline:#b91c1c;}')
    $null = $sb.AppendLine('@media (prefers-color-scheme:dark){:root{--bg:#16181d;--fg:#e6e6e6;--muted:#9aa0a6;--line:#2c3038;--pipeline:#1e3a5f;--yaml:#14352a;--repo:#4a3a12;--bad:#4a1d1d;--badline:#f87171;}}')
    $null = $sb.AppendLine('*{box-sizing:border-box}body{margin:0;padding:2rem;background:var(--bg);color:var(--fg);font:14px/1.55 "Segoe UI",system-ui,-apple-system,Helvetica,Arial,sans-serif}')
    $null = $sb.AppendLine('h1{font-size:1.4rem;margin:0 0 .25rem}h2{font-size:1.05rem;margin:2rem 0 .6rem;padding-bottom:.3rem;border-bottom:1px solid var(--line)}')
    $null = $sb.AppendLine('.sub{color:var(--muted);margin:0 0 1.5rem}')
    $null = $sb.AppendLine('.tiles{display:flex;gap:.75rem;flex-wrap:wrap;margin:1rem 0}')
    $null = $sb.AppendLine('.tile{border:1px solid var(--line);border-radius:8px;padding:.6rem .9rem;min-width:8rem}')
    $null = $sb.AppendLine('.tile b{display:block;font-size:1.5rem;line-height:1.1}.tile span{color:var(--muted);font-size:.8rem}')
    $null = $sb.AppendLine('.wrap{overflow-x:auto}table{border-collapse:collapse;width:100%;font-size:.85rem}')
    $null = $sb.AppendLine('th,td{text-align:left;padding:.35rem .6rem;border-bottom:1px solid var(--line);vertical-align:top}')
    $null = $sb.AppendLine('th{color:var(--muted);font-weight:600;white-space:nowrap}')
    $null = $sb.AppendLine('code{font:12px/1.4 ui-monospace,"Cascadia Mono",Consolas,monospace}')
    $null = $sb.AppendLine('.k{display:inline-block;padding:.05rem .45rem;border-radius:999px;font-size:.72rem;border:1px solid var(--line)}')
    $null = $sb.AppendLine('.k-pipeline{background:var(--pipeline)}.k-yaml{background:var(--yaml)}.k-repo{background:var(--repo)}')
    $null = $sb.AppendLine('.k-unresolved{background:var(--bad);border-color:var(--badline);color:var(--badline);font-weight:600}')
    $null = $sb.AppendLine('tr.bad td{background:var(--bad)}')
    $null = $sb.AppendLine('</style></head><body>')

    $null = $sb.AppendLine("<h1>Pipeline dependency graph</h1>")
    $null = $sb.AppendLine("<p class=""sub"">$(& $esc $Graph.organisation) / $(& $esc $Graph.project) &middot; generated by <code>$(& $esc $Graph.generatedBy)</code></p>")

    $null = $sb.AppendLine('<div class="tiles">')
    foreach ($group in $byKind) {
        $null = $sb.AppendLine("<div class=""tile""><b>$($group.Count)</b><span>$(& $esc $group.Name) nodes</span></div>")
    }
    $null = $sb.AppendLine("<div class=""tile""><b>$(@($Graph.edges).Count)</b><span>edges</span></div>")
    $null = $sb.AppendLine("<div class=""tile""><b>$($unresolved.Count)</b><span>unresolved</span></div>")
    $null = $sb.AppendLine('</div>')

    if ($unresolved.Count) {
        $null = $sb.AppendLine('<h2>Unresolved references</h2>')
        $null = $sb.AppendLine('<div class="wrap"><table><thead><tr><th>From</th><th>Reference</th><th>Kind</th><th>Reason</th></tr></thead><tbody>')
        foreach ($edge in $unresolved) {
            $null = $sb.AppendLine("<tr class=""bad""><td><code>$(& $esc $edge.from)</code></td><td><code>$(& $esc $edge.ref)</code></td><td>$(& $esc $edge.refKind)</td><td><span class=""k k-unresolved"">$(& $esc $edge.reason)</span></td></tr>")
        }
        $null = $sb.AppendLine('</tbody></table></div>')
    }

    $null = $sb.AppendLine('<h2>Nodes</h2>')
    $null = $sb.AppendLine('<div class="wrap"><table><thead><tr><th>Id</th><th>Kind</th><th>Name</th><th>Repository</th><th>Path</th><th>In</th></tr></thead><tbody>')
    foreach ($node in $Graph.nodes) {
        $in = if ($inDegree.ContainsKey($node.id)) { $inDegree[$node.id] } else { 0 }
        $repo = if ($node.PSObject.Properties['repo']) { $node.repo } else { '' }
        $path = if ($node.PSObject.Properties['path']) { $node.path } else { '' }
        $null = $sb.AppendLine("<tr><td><code>$(& $esc $node.id)</code></td><td><span class=""k k-$(& $esc $node.kind)"">$(& $esc $node.kind)</span></td><td>$(& $esc $node.name)</td><td>$(& $esc $repo)</td><td><code>$(& $esc $path)</code></td><td>$in</td></tr>")
    }
    $null = $sb.AppendLine('</tbody></table></div>')

    $null = $sb.AppendLine('<h2>Edges</h2>')
    $null = $sb.AppendLine('<div class="wrap"><table><thead><tr><th>From</th><th>To</th><th>Kind</th><th>Reference</th><th>Alias</th></tr></thead><tbody>')
    foreach ($edge in $Graph.edges) {
        $bad = if ($edge.kind -eq 'unresolved') { ' class="bad"' } else { '' }
        $ref = if ($edge.PSObject.Properties['ref']) { $edge.ref } else { '' }
        $alias = if ($edge.PSObject.Properties['alias']) { $edge.alias } else { '' }
        $pseudo = if ($real.ContainsKey($edge.to)) { '' } else { ' &#9888;' }
        $null = $sb.AppendLine("<tr$bad><td><code>$(& $esc $edge.from)</code></td><td><code>$(& $esc $edge.to)</code>$pseudo</td><td><span class=""k k-$(& $esc $edge.kind)"">$(& $esc $edge.kind)</span></td><td><code>$(& $esc $ref)</code></td><td>$(& $esc $alias)</td></tr>")
    }
    $null = $sb.AppendLine('</tbody></table></div>')

    $null = $sb.AppendLine('<p class="sub">&#9888; marks an edge endpoint that is not a real node: a reference that could not be resolved.</p>')
    $null = $sb.AppendLine('</body></html>')

    $sb.ToString()
}
